(define-module (myguix packages llm)
  #:use-module ((guix licenses)
                #:prefix license:)
  #:use-module (myguix packages cuda)
  #:use-module (myguix packages nvidia)
  #:use-module (guix packages)
  #:use-module (guix gexp)
  #:use-module (guix git-download)
  #:use-module (guix build-system cmake)
  #:use-module (gnu packages python)
  #:use-module (gnu packages pkg-config))

